import {ClerkProvider,} from '@clerk/nextjs'
import { Cairo } from "next/font/google";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
const inter = Cairo({ subsets: ["latin"] });
import "./globals.css";


export const metadata = {
  title: "متجركو",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en" dir="rtl">
            <body className={inter.className}>
                <Header/>
                {children} 
                <Footer/>
            </body>
        </html>
    </ClerkProvider>
  );
}
